ARG NODE_VERSION=24-slim

FROM node:${NODE_VERSION}
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3001
EXPOSE 3001
CMD ["npm", "run", "dev:docker"]
